language: go

go:
  - 1.15.3

env:
  - GOSUMDB=off

script:
  - go get
  - go test -v github.com/OperatorFoundation/shapeshifter-dispatcher/common/socks5
  - cd shTests/TransparentTCP
  #- ./testTCPDust.sh
  #- ./testTCPMeek.sh
  - ./testTCPObfs2.sh
  - ./testTCPObfs4.sh
  - ./testTCPOptimizerFirst.sh
  - ./testTCPOptimizerMinimizeDialDuration.sh
  - ./testTCPOptimizerRandom.sh
  - ./testTCPOptimizerRotate.sh
  - ./testTCPOptimizerTrack.sh
  - ./testTCPReplicant.sh
  - ./testTCPShadow.sh
  - cd ../TransparentUDP
  #- ./testUDPDust.sh
  #- ./testUDPMeek.sh
  - ./testUDPObfs2.sh
  - ./testUDPObfs4.sh
  - ./testUDPOptimizerFirst.sh
  - ./testUDPOptimizerMinimizeDialDuration.sh
  - ./testUDPOptimizerRandom.sh
  - ./testUDPOptimizerRotate.sh
  - ./testUDPOptimizerTrack.sh
  - ./testUDPReplicant.sh
  - ./testUDPShadow.sh
  - cd ../StunUDP
  #- ./testStunUDPDust.sh
  #- ./testStunUDPMeek.sh
  - ./testStunUDPObfs2.sh
  - ./testStunUDPObfs4.sh
  - ./testStunUDPOptimizerFirst.sh
  - ./testStunUDPOptimizerMinimizeDialDuration.sh
  - ./testStunUDPOptimizerRandom.sh
  - ./testStunUDPOptimizerRotate.sh
  - ./testStunUDPOptimizerTrack.sh
  - ./testStunUDPReplicant.sh
  - ./testStunUDPShadow.sh
  - cd ../SocksTCP
  #- ./testSocksTCPDust.sh
  #- ./testSocksTCPMeek.sh
  - ./testSocksTCPObfs2.sh
  - ./testSocksTCPObfs4.sh
  - ./testSocksTCPOptimizerFirst.sh
  - ./testSocksTCPOptimizerMinimizeDialDuration.sh
  - ./testSocksTCPOptimizerRandom.sh
  - ./testSocksTCPOptimizerRotate.sh
  - ./testSocksTCPOptimizerTrack.sh
  - ./testSocksTCPReplicant.sh
  - ./testSocksTCPShadow.sh
  #- cd ../Other
  #- ./testIPCLogLevel.sh
  #- ./testReducedMicroformats.sh